### ISSUE TITLE
Constant progress wheel when using base search and post processing

### ISSUE THREAD

**Issue by dariusdiederich** [sghaskell/maps-plus#13]
Hello,

I am currently running Splunk 7.2.8 with Maps+ viz 3.1.2 in a Chrome Version 78.0.3904.97 browser.

Noticing that when using a base search the visualization does not zoom correctly and displays a constant progress wheel.

If I use the same search inline it works as expected.  

I saw in a different Issue reported you specifically asked if the user was using a base search so I'm hoping this could be a known issue you've seen or have a suggestion how to correct.

Also confirmed that Splunk 7.2.8 with Maps+ viz 2.0.7 the same occurs.

I did not have this trouble with Splunk 6.5.9 with Maps+ viz 2.0.7.

Thanks!
Darius

**Comment by sghaskell** [comment]
Greetings, @dariusdiederich . Thanks for reaching out. There is a shortcoming in the Custom Visualization API around using base searches. As such, they don't reliably work with the viz. I'd convert the viz to use the full search.
