### ISSUE TITLE
issue when using dashboard tokens in the base search

### ISSUE THREAD

**Issue by akshaykaul** [sghaskell/maps-plus#2]
HI, 
we are using maps plus app on splunk enterprise 6.4. The dashboard simply plots the markers based on the value of the tokens (from dropdown menus) in the dashboard. 
eg. when value "A" is selected from the dropdown - the base search calculates the lat long and other marker Parameters based on that and renders the markers on the map fine.
But then if a diff token value "B" is selected from the dropdown then the new set of markers do get plotted but the previously rendered markers (relevant to value A) also stay on the map. Its like the map panel does not get refreshed. Although it works ok , if we refresh the browser after selecting a diff token value but thats not ideal.

Any help or insight would be appreciated.

Thank you.

**Comment by akshaykaul** [comment]
HI,
update:

we have tested this on splunk 7.1 and it works fine.

**Comment by sghaskell** [comment]
Hi @akshaykaul. I've been contemplating removing support for 6.x due to issues with how the Custom Visualization API handles pagination of data and dashboard interaction. My recommendation would be to upgrade to 7.x.

**Comment by akshaykaul** [comment]
Thank you scott.
Yes we are in the process of upgrading soon its just that we have been using the original cluster map viz app and wanted to use some cool features of the new plus app (like circle markers/heatmaps) .
Also noticed that since we installed the maps + on our 6.x instance the legacy cluster map  viz  has started to throw some exceptions as well when used with token. eg:  Error rendering (Legacy) Clustered Single Value Map Visualization visualization. 
Now thinking about rolling back the app on our SHC - was not sure if they can co-exist.

Thank you
Akshay.

**Comment by sghaskell** [comment]
You may want to roll back until you upgrade to 7.x. Maps+ comes with a legacy version of Clustered Single Value Maps Visualization (1.5.17), but it may not be the version you were using previously.

**Comment by sghaskell** [comment]
Closing this out as I've removed support for Splunk 6.x in version 3.x of Maps+ for Splunk. If you continue to have problems after upgrading, please re-open.
