### ISSUE TITLE
PNG Markers missing "Yellow".

### ISSUE THREAD

**Issue by greggwoodcock** [sghaskell/maps-plus#22]
Yellow is a standard color both in the colors of the rainbow AND in the primary colors of pigment are magenta, yellow, and cyan.  This is a glaring oversight for anybody who uses "stoplight" colors for anything (Red/Yellow/Green).

**Comment by sghaskell** [comment]
I use [Leaflet.awesome-markers](https://github.com/lvoogdt/Leaflet.awesome-markers) under the covers for the PNG markers. Unfortunately, they don't include yellow. Here's their [marker palette](https://github.com/lvoogdt/Leaflet.awesome-markers/blob/2.0/develop/dist/images/markers-plain.png). 

The best workaround would be to use [SVG markers `markerColor`](https://github.com/sghaskell/maps-plus#markercolor-1) to customize using HTML Color code or Hex value.
