### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pgthompson** [sghaskell/maps-plus#3]
Hey Scott
Love the Maps+ app! (trying it out in Ver 7.14). Are there any plans to apply the markerPriority to the  new circle (canvas) markers? I've tried getting it to work, unsuccessfully.
e.g. eval markerPriority=if(Site="Site A","1000","-1000")
Site A renders below others. 
Cheers Paul Thompson

**Comment by sghaskell** [comment]
Hey Paul. Let me look into this. It's likely just an oversight on my part when I added the new feature. I'll do some testing and let you know.

**Comment by pgthompson** [comment]
Hi there Scott

Just wondering when you might have an updated version that caters for the canvas marker priority?

Thanks, Paul

**Comment by sghaskell** [comment]
Hi Paul,

Apologies for not getting to this sooner. I've got some new features I'll be pushing out shortly so I'll look to incorporate this fix into the release. Thanks for your patience!

**Comment by sghaskell** [comment]
Hi @pgthompson 

I'm looking into this now. You can only set a `zIndexOffset` on a [Marker](https://leafletjs.com/reference-1.3.0.html#marker-zindexoffset) which is considered a UI layer. The [CircleMarker](https://leafletjs.com/reference-1.3.0.html#circlemarker) is a vector layer and it doesn't have a similar functionality. The only viable thing I can see is using he method [bringToFront](https://leafletjs.com/reference-1.3.0.html#circlemarker-bringtofront) but that would require grouping markers into layers. You'd be limited to bringing only one layer to the front via SPL. I could add a context menu when right clicking on a circle to bring its layer to the front, but that requires interaction with the map. It appears there's no simple way to accomplish something similar to `markerPriority` using vector layers.

**Comment by sghaskell** [comment]
I'm digging a bit deeper and it looks like you can create new [panes](https://leafletjs.com/reference-1.3.0.html#map-overlaypane) and specify their Z-Index. I'll play with this and see if it's a viable solution.

**Comment by pgthompson** [comment]
Thanks Scott, appreciate your great work!
Paul

**Comment by pgthompson** [comment]
Awesome Scott! Looking forward to the new release
Paul

**Comment by sghaskell** [comment]
Hi @pgthompson - Sorry for the delay in getting this to you. Could you try out this branch to see if it meets your expectations?

https://github.com/sghaskell/maps-plus/tree/feature/vector-path-enhancements

Use the new SPL field`layerPriority` in conjunction with `layerGroup` when using circle markers or paths (polylines). It behaves the same way as `markerPriority`.

**Comment by pgthompson** [comment]
Hi Scott
Sorry but I’m fairly basic javascript user. I downloaded visualization.js from Git ok.

I set those 2 values to this (using similar logic to markerPriority but wasn’t too sure about arguments for layerGroup so just set the same as priority)
layerPriority=if(like(description,"%COW%"),"1000","900"),layerGroup=if(like(description,"%COW%"),"1000","900")

Without running the new js my map seemed to prioritise the circles ok initially (with both layers on) which is kind of interesting.

[cid:image001.png@01D4EB9F.5AAB9A30]


When I hide the ‘green’ layer and then unhide again it renders on top
[cid:image004.jpg@01D4EB9F.A5020F10]

I then ran visualization.js in FF scratchpad but it didn’t seem to have any effect so I’m not sure if I’m doing something wrong trying to run the js this way or have the layer values wrong.
Cheers Paul

**Comment by sghaskell** [comment]
Hi @pgthompson - Did you add `layerGroup` and `layerPriority` in your final table command? - `| table layerGroup, layerPriority` You will also need to re-start Splunk after dropping visualization.js into the app. You may also have the old version cached in your browser. Try clearing your browser cache.

**Comment by pgthompson** [comment]
Hi Scott

I managed to add visualization.js to the app and restart and it worked a treat after that!  The canvas  markers are prioritising as desired.
Thanks 😊

**Comment by sghaskell** [comment]
Thanks for confirming @pgthompson . I hope to get the release out this week with this feature and a bunch of others.

**Comment by sghaskell** [comment]
Hi @pgthompson . This has been addressed in [v3.0.1](https://github.com/sghaskell/maps-plus/releases/tag/3.0.1). See [layer priority](https://github.com/sghaskell/maps-plus#layer-priority).
