### ISSUE TITLE
App vetting for Splunk Cloud

### ISSUE THREAD

**Issue by s-m-p** [sghaskell/maps-plus#33]
Do you anticipate passing the latest version (3.1.5) through the Cloud vetting process? As it stands right now, I cannot upgrade this app because it is not cloud-vetted according to Splunbase:
![image](https://user-images.githubusercontent.com/38626196/181523935-e28c33db-bc1c-4779-9652-e398a6a32121.png)

**Comment by sghaskell** [comment]
The latest version 3.1.8 is now available for Cloud. Apologies for the delay. The Cloud Vetting app process can be slow.
