### ISSUE TITLE
Splunk support will not upgrade in Splunk Cloud

### ISSUE THREAD

**Issue by s-m-p** [sghaskell/maps-plus#35]
I have v3.1.4 installed on our Cloud stack. Yesterday I requested this app be upgraded, and this was the response:
> Note: https://splunkbase.splunk.com/app/3124/ is not supported by Splunk and thus we won't be able to upgrade that

Have you encountered Cloud customers who couldn't upgrade your app?

**Comment by sghaskell** [comment]
Hi @s-m-p . The app is currently supported for Splunk Cloud Classic and Victoria so there shouldn't be any compatibility issues. I'm wondering if you account possibly transitioned from support upgrades to self service app install? I believe you need to have sc_admin role to install apps.

https://docs.splunk.com/Documentation/SplunkCloud/9.0.2205/Admin/SelfServiceAppInstall

**Comment by s-m-p** [comment]
Thanks for the response. I have the sc_admin role, so that's not the cause. Although I'm a bit unclear about what you mean by "transitioned", but he app is noted as a Splunkbase app in our apps list, so it is not denoted for SSAI. There is an 'Update Available' link, but the dialog box says "You cannot update Maps+ for Splunk (version 3.1.4) by using self-service app installation. To update this app, contact Splunk Support.".

I can't find any explanation for this position taken by Support, although it's not the first time. I am going to discuss this today with my AE to see if he can think of an explanation. I'm also going to ask support to re-evaluate their position on this app.

**Comment by sghaskell** [comment]
Thanks for the update @s-m-p . I'd recommend talking to your account team to see if they can escalate this with support. That line of reasoning that it's community supported so they can't upgrade it, when it's vetted by Splunk Appinspect for Classic and Victoria makes no sense to me.

**Comment by s-m-p** [comment]
I pushed back a little and they did end up upgrading the app. I never got an explanation as to why the request was denied initially.

**Comment by sghaskell** [comment]
Thanks for the update @s-m-p . Perhaps it was someone new in support? Glad you got it upgraded!
