### ISSUE TITLE
Splunk maps Tile Override

### ISSUE THREAD

**Issue by OsmaryA** [sghaskell/maps-plus#4]
HI,

we are using the previous version of splunk maps, and now upgrade to this, but we have a option that use a TilesOverride, and let be choose for a token, and now is not working.

This is an example of my code:

 <option name="leaflet_maps_app.maps-plus.Tile">http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png</option>
        <option name="leaflet_maps_app.maps-plus.TileOverride">http://mt1.google.com/vt/lyrs=$tile$&amp;x={x}&amp;y={y}&amp;z={z}</option>

And for the token:

   <choice value="y">Satelital</choice>
      <choice value="m">Mapa</choice>
      <choice value="p">Terreno</choice>

Please can you confirm that this option continues to work?

Thanks a lot.

This is how looks now:
![imagen](https://user-images.githubusercontent.com/45854969/49952421-31789580-fefc-11e8-91b8-a938477504da.png)

**Comment by sghaskell** [comment]
@OsmaryA 

It should work just fine. It seems the token values you're passing to `lyrs` are not valid. Have a look here.

https://answers.splunk.com/answers/186394/how-to-specify-google-maps-url-for-map-tiles-in-sp.html

Just update the token values to the correct `lyrs` value and it should work fine. Here's an example using `p` (terrain).

http://mt1.google.com/vt/lyrs=p&x={x}&y={y}&z={z}

<img width="1624" alt="screen shot 2018-12-13 at 9 00 48 am" src="https://user-images.githubusercontent.com/8450537/49954612-b2f90500-feb5-11e8-9d48-140dbc1d11d4.png">
