### ISSUE TITLE
Path Lines - Add Direction or Gradiant

### ISSUE THREAD

**Issue by ericmck2000** [sghaskell/maps-plus#6]
This is a request to add either a... gradient or direction indicator to path lines so users of the dashboard/visualization can easily see the "Flow"  of data.

I have implemented the gradient method- however- it plots the path lines as a single continuous path, which is good- but, it does not allow me to easily color the path based on the time, or completion.

**Comment by sghaskell** [comment]
Hi @ericmck2000 

Thanks for the feature request. This is actually coming in an upcoming release. The code is complete but there are a few other features I'm releasing it with that are holding things up. I hope to get it out in a few weeks. It's implemented as an animated ant-path line to show you direction flow using the [leaflet-ant-path plugin](https://rubenspgcavalcante.github.io/leaflet-ant-path/).

Is this along the lines of what you're looking for?

**Comment by ericmck2000** [comment]
That looks even better then my idea.

Here is my current workaround.
![image](https://user-images.githubusercontent.com/5262735/55756881-35cf3e00-5a18-11e9-8aec-8b99692ab4fb.png)

**Comment by sghaskell** [comment]
This has been addressed in version 3.0.1. See [path direction](https://splunkbase.splunk.com/app/3124/)
