### ISSUE TITLE
Add ability to "Animate"

### ISSUE THREAD

**Issue by ericmck2000** [sghaskell/maps-plus#7]
Add the ability to animate data over time.

Example: https://splunkbase.splunk.com/app/3217/

This app, has the ability to click play, and plot the data over time. This functionality would be great to be included in Maps+.

**Comment by ericmck2000** [comment]
A few examples of its implementation:

![image](https://user-images.githubusercontent.com/5262735/55756978-6f07ae00-5a18-11e9-8e1c-2a74835ca915.png)


![image](https://user-images.githubusercontent.com/5262735/55756988-762ebc00-5a18-11e9-93b7-ceee3d7357f3.png)

**Comment by sghaskell** [comment]
Check out the latest [3.1.0 release](https://github.com/sghaskell/maps-plus/releases/tag/3.1.0) for path playback capability. Have a look at the **Path Playback** example dashboard.

**Comment by ericmck2000** [comment]
Thanks! Tested the feature, and it seems to work well.

One piece of feedback- the playback speed multiplier does not seem to be working as I would expect.

I have modified the default value, adding 0s to the end for every test interation- and it still seems to be going second by second, instead of being able to speed it up.

**Comment by ericmck2000** [comment]
Disregard me- I determined I need to modify the Tick Length.

**Comment by ericmck2000** [comment]
Although- The slider does NOT work as expected. It will scroll back to the start of epoch time, making it unsuitable for looking at a set of data which only goes back one day.

I would recommend setting its values to the latest, and earliest event.

**Comment by sghaskell** [comment]
Thanks @ericmck2000. It shouldn't reset to epoch time. It should default to earliest/latest for all the tracks in the playback. Can you reproduce what you're seeing?

**Comment by ericmck2000** [comment]
Yes- I reproduced the issue using this search.

| makeresults count=1
| eval latitude=0, longitude=0, _time=NOW()
